### ISSUE TITLE
[AndroidOS] Enhancement: Figma Specs

### ISSUE THREAD

**Issue by KhaledChehabeddine** [SweepLebanon/Pixel-AndroidOS#24]
# Overview

- Add the specs from [Figma](https://www.figma.com/file/Y3zbLp7XzGtLegWLBAl1VI/Design-Resources---V1.0.0?type=design&node-id=0-1&mode=design)

# Subtasks
- [ ] [Figma Specs Colors](https://github.com/SweepLebanon/Pixel-AndroidOS/issues/19)
- [ ] [Figma Specs Fonts](https://github.com/SweepLebanon/Pixel-AndroidOS/issues/20)
- [ ] [Figma Specs Icons](https://github.com/SweepLebanon/Pixel-AndroidOS/issues/21)
- [ ] [Figma Specs Spacing](https://github.com/SweepLebanon/Pixel-AndroidOS/issues/22)
- [ ] [Figma Specs Buttons](https://github.com/SweepLebanon/Pixel-AndroidOS/issues/23)
